name: Deploy Next.js App

on:
  push:
    branches:
      - master  # Автодеплой при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Устанавливаем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # 4. Сборка приложения
      - name: Build Next.js project
        run: npm run build

      # 5. Деплой файлов через SCP (с использованием пароля)
      - name: Deploy files via SCP
        run: |
          sshpass -p ${{ secrets.REMOTE_PASSWORD }} scp -r . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/фуфелмаркет.рф

      # 6. Перезапуск приложения через SSH (с использованием пароля)
      - name: Restart application
        run: |
          sshpass -p ${{ secrets.REMOTE_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd /var/www/фуфелмаркет.рф
          npm install
          pm2 restart фуфелмаркет.рф || pm2 start npm --name "фуфелмаркет.рф" -- start
          pm2 save
          EOF
